---
title: "??????????????, ???????????? ???????????????? ????????????"
author: "???????? ????????????????????"
date: "???????????? 2018"
output: 
  html_document:
    toc: true
    toc_depth: 3
    fig_width: 10
    fig_height: 6
---


## ?????????????? 7

???????????? ?????????????????????? ?????????????? ?????????????????????????? ??.??. ?? ?????????????????? ??????????????????????????.

$$
P\{X = 1\} = 0.3 \\
P\{X = 2\} = 0.2 \\
P\{X = 3\} = 0.35 \\
P\{X = 4\} = 0.15 \\
$$

```{r}
sampleDist = function(n) { #?????? n - ???????????? ??????????????
  sample(x = c(1,2,3,4), n, replace = T, prob = c(0.3, 0.2, 0.35, 0.15)) 
}

sampleDist(40)
```

## ?????????????? 16

?????? ?????????????????????? ???????????????????? ???????????????????????????? ??.??. ?????????? ?????????????? [0;1] ???? ?????? ??????????. ?????????????????? ???????????????? ?????????????????????? ???? ???????????????????? ?????????????? 1000 ??????. a) ?????????????????? ???????????????????????? ?????????????? ?????????????????? ???????? ??????????, ?????????????? ?? ???????????? ????????????. ??) ?????????? (????????????????????????) ??????????? ??) ?????????????????????? ???????????????????? ???????????????????????? ?????????? ???????????????????????????? ?????????????????? ?????????????? ??????????????????????????.

??????????????????????, ???? ?????????? $n$ ?????????????????????? ???????????????????? ?????????????????????????? ????????????????. ?? ?????????? ???????????? $n = 2$.

$$X_i \sim U(0,1), i=1 \ldots n$$

?????????????? ?????????????????????????? ?????? ???????????????? $Y=\min(X_1,\ldots, X_n)$ ??.??. ?????????? ??????????:

$$
\begin{array}{lclr}
p(Y \leq x) & = & 1 - p(Y \geq x) & \\
            & = & 1- \prod_{i=1}^n p(X_i \geq x) & \color{blue}{ Y = \min(X_i) } \\
            & = & 1- p(X \geq x)^n & \color{blue}{ X_i~\text{iid}~ X \sim U(0,1) } \\
            & = & 1- (1-p(X \leq x))^n & \\
            & = & 1- (1-x)^n & \color{blue}{ p(X \leq x) = x } \\
\end{array}
$$

?????????? ?????????????? ?????????????????? ???????????????????? ?????? $Y$:

$$f_Y(x) = \frac{d}{dx} P(Y \leq x) = n(1-x)^{n-1}$$
???????????????? ?????????????? 1000 ?????? ?????? $n = 2$ ?? ???????????????? ??????????????????????:

```{r}
n <- 2
pdf.min <- function(x) {  # ?????????????? ?????????????????? ?????????????????????? ?????? ?????????? ??????????
  n*(1-x)^(n-1)
}
sample.min <-  function() { # ?????????????? ?????????????? 
  min(runif(n))
}
sim.min <- replicate(1000, sample.min()) # ?????????????????? 1000 ??????
hist(sim.min, breaks=50, prob=T, main="pdf of Y")
curve(pdf.min, 0, 1, col="red", lwd=2, add=T)
```

???? ???? ?????????? ?????? ?????????????????? $Z = \max(X_1,\ldots, X_n)$ ??.??. ???????????? ??????????:

$$
\begin{array}{lclr}
p(Z \leq x) & = & \prod_{i=1}^n p(X_i \geq x) & \\
            & = & x^n & \color{blue}{ p(X \leq x) = x } \\
\end{array}
$$

?????????? ?????????????? ?????????????????? ?????????????????????? $Z$:

$$f_Z(x) = nx^{n-1}$$

?? ?????? ??????:

```{r}
n <- 2
pdf.max <- function(x) {    
  n*x^(n-1)
}
sample.max <-  function() { 
  max(runif(n))
}
sim.max <- replicate(1000, sample.max()) 
hist(sim.max, breaks=50, prob=T, main="pdf of Z")
curve(pdf.max, 0, 1, col="red", lwd=2, add=T)
```

?????????????????????? ?????????????????????????? ?????????????????????? ?????? ???????????????? ?????????????? $R=Z-Y$:

```{r}
hist(sim.max-sim.min, breaks=50, prob=T, main="approximate pdf of R=Z-Y")
```

**?????????????????? ?????? ???????????????? ?????????????? ?????? ??????????????????.** 

### ???????????????????????? ??????????

??.??. $n=2$, ?????????????? ?????????????????? ?????????? ?? ???????????? ?????????? ??????????????. ???????????????? ????????????????????????:

$$ 
f_Y(x) = n(1-x)^{n-1} \\
f_Y(x) = 2(1-x)
$$

$$
f_Z(x) = nx^{n-1}
f_Z(x) = 2x
$$

## ?????????????? 17

??????????????????????, ???????????????????????????? ?????????????????? ????????????????, ???????????????????? ?????????? ????????????????????. ????????????????, ?????? ???? 142 ???????????????? ???????? 9 ???????????? ?? ????????????????????????. ?? ???????????????? ??????????????????, ?????? ?? ?????????????? 10% ???????????????? ???????????????? ???????????????? ?? ????????????????????????. ?????????? ???? ??????????????, ?????? ???????????????????? ?????????????????????? ?????????????? ?????????? ?????????????????? ???????? ?????? ???? ???????????? ?????????????? ???????????????????? ?????? ??????????????????????. ???????????????????? ?????????????????? ???????????????? ???????????????? ?? ???????????? P-???????????????? (?????????? ???????????????????????? ??????????????????).

**Null-Hypothesis:** ?????????????????? ???????????? ?????????????? ???? ?????????????? ?????????? ?????????????????? ????????.

```{r}

sim_samples <- function(n, p = 0.1) {
  x <- c()
  for (i in 1:n) {
    set.seed(123 + i)
    simulated_sample <- runif(142) < p
    x[i] <- sum(simulated_sample == TRUE)
  }
  return(x)
}

x = sim_samples(1000)

a = mean(x)
sd = sqrt(var(x))
right = qnorm(0.975, mean = a, sd = sd)
left = qnorm(0.025, mean = a, sd = sd)
pval = pnorm(9, mean = a, sd = sd)

hist(x, breaks=20, main = "1k samples")
abline(v = 9, col = 4)
abline(v = right, col = 2)
abline(v = left, col = 2)

```

9 ???????????????????? ???? 142 (??????????) ???????????????? ???????????????? ?? ?????????????????????????? ???????????????? (??????????????), ?????? ????????????????, ?????? ?? ?????? ?????? ?????????????????? ???????????????????? ?????????????? ????????????????. ???????????????????? ???????????? ???? ?????????????? ???????? ???????????????????? ???? ?????????? ???????????????? (p-value = 0.0748).
